// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package java2slice.orig;

public abstract class Callback_TestClassSupplier_get
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<java2slice.orig.TestClassIce>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        TestClassSupplierPrxHelper.__get_completed(this, __result);
    }
}
