// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package java2slice.orig;

public final class TestClassSupplierHolder extends Ice.ObjectHolderBase<TestClassSupplier>
{
    public
    TestClassSupplierHolder()
    {
    }

    public
    TestClassSupplierHolder(TestClassSupplier value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof TestClassSupplier)
        {
            value = (TestClassSupplier)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _TestClassSupplierDisp.ice_staticId();
    }
}
