// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package java2slice.orig;

public interface TestClassSupplierPrx extends Ice.ObjectPrx
{
    public TestClassIce get();

    public TestClassIce get(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_get();

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_get(Ice.Callback __cb);

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_get(Callback_TestClassSupplier_get __cb);

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, Callback_TestClassSupplier_get __cb);

    public Ice.AsyncResult begin_get(IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_get(IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public TestClassIce end_get(Ice.AsyncResult __result);
}
