// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package java2slice.orig;

public interface TestClassSupplier extends Ice.Object,
                                           _TestClassSupplierOperations, _TestClassSupplierOperationsNC
{
    public static final String ice_staticId = "::java2slice::orig::TestClassSupplier";

    public static final long serialVersionUID = 3020915695103324604L;
}
