// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `foo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package java2slice.orig;

/**
 * Provides type-specific helper functions.
 **/
public final class TestClassSupplierPrxHelper extends Ice.ObjectPrxHelperBase implements TestClassSupplierPrx
{
    private static final String __get_name = "get";

    public TestClassIce get()
    {
        return get(null, false);
    }

    public TestClassIce get(java.util.Map<String, String> __ctx)
    {
        return get(__ctx, true);
    }

    private TestClassIce get(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__get_name);
        return end_get(begin_get(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_get()
    {
        return begin_get(null, false, false, null);
    }

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx)
    {
        return begin_get(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_get(Ice.Callback __cb)
    {
        return begin_get(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_get(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_get(Callback_TestClassSupplier_get __cb)
    {
        return begin_get(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, Callback_TestClassSupplier_get __cb)
    {
        return begin_get(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_get(IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_get(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_get(IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_get(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_get(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_get(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.Functional_GenericCallback1<TestClassIce> __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_get(__ctx, __explicitCtx, __synchronous, 
                         new IceInternal.Functional_TwowayCallbackArg1<java2slice.orig.TestClassIce>(__responseCb, __exceptionCb, __sentCb)
                             {
                                 public final void __completed(Ice.AsyncResult __result)
                                 {
                                     TestClassSupplierPrxHelper.__get_completed(this, __result);
                                 }
                             });
    }

    private Ice.AsyncResult begin_get(java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__get_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__get_name, __cb);
        try
        {
            __result.prepare(__get_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public TestClassIce end_get(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __get_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            TestClassIceHolder __ret = new TestClassIceHolder();
            __is.readObject(__ret);
            __is.readPendingObjects();
            __result.endReadParams();
            return __ret.value;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __get_completed(Ice.TwowayCallbackArg1<TestClassIce> __cb, Ice.AsyncResult __result)
    {
        java2slice.orig.TestClassSupplierPrx __proxy = (java2slice.orig.TestClassSupplierPrx)__result.getProxy();
        TestClassIce __ret = null;
        try
        {
            __ret = __proxy.end_get(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestClassSupplierPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestClassSupplierPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestClassSupplierPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static TestClassSupplierPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static TestClassSupplierPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static TestClassSupplierPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, TestClassSupplierPrx.class, TestClassSupplierPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::java2slice::orig::TestClassSupplier"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, TestClassSupplierPrx v)
    {
        __os.writeProxy(v);
    }

    public static TestClassSupplierPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            TestClassSupplierPrxHelper result = new TestClassSupplierPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
